backend:
  name: git-gateway
  branch: main
media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: pages
    label: Pages
    i18n:
      structure: single_file
      locales: [en, es]
    files:
      - name: home
        label: Home
        file: site/content/home.yml
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
