backend:
  name: git-gateway
  branch: main
media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "home" # Used in routes, e.g., /admin/collections/blog
    label: "Home" # Used in the UI
    folder: "_posts/home" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
