backend:
  name: git-gateway
  branch: main
media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/" # The src attribute for uploaded media will begin with /images/uploads
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, es]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: "home"
    i18n: true
    create: true
    folder: content
    label: "Home"
    identifier_field: slug
    fields:
      - label: "Slug"
        name: "slug"
        widget: "hidden"
        default: "home"
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Date
        name: date
        widget: datetime
        i18n: duplicate
      - label: Body
        name: body
        widget: markdown
