backend:
  name: git-gateway
  branch: main
media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/" # The src attribute for uploaded media will begin with /images/uploads
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, es]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: "pages"
    i18n: true
    create: true
    format: "json"
    folder: content
    label: "Pages"
    identifier_field: slug
    fields:
      - label: "Slug"
        name: "slug"
        widget: "hidden"
        default: "home"
        i18n: duplicate
      - label: Metadata
        name: metadata
        widget: object
        summary: "{{fields.titulo}}"
        i18n: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Description",
              name: "description",
              widget: "string",
            }
      - label: Header
        name: header
        widget: object
        i18n: true
        fields:
          - label: "Logo"
            name: "logo"
            widget: "image"
          - label: "Links"
            name: "links"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Link, name: link, widget: string }
          - label: Button
            name: button
            widget: object
            summary: "{{fields.title}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
      - label: Hero
        name: hero
        widget: object
        i18n: true
        fields:
          - label: "Text"
            name: "text"
            widget: "string"
          - label: "Highlighted text"
            name: "highlight"
            widget: "string"
          - label: "Background image"
            name: "background"
            widget: "image"
      - label: Sections
        name: sections
        i18n: true
        widget: list
        summary: "{{fields.type}}"
        hint: "Depending on the type you select, it will show different sections and information. Only fill the fields specific to the section you want to display."
        fields:
          - label: Type
            name: type
            widget: select
            options:
              - { label: "Text", value: "TEXT" }
              - {
                  label: "Text, Image Right",
                  value: "TEXT_IMAGE_RIGHT",
                }
              - {
                  label: "Text, Image Left",
                  value: "TEXT_IMAGE_LEFT",
                }
              - { label: "Numbers", value: "NUMBERS" }
              - { label: "Carousel", value: "CAROUSEL" }
              - { label: "Gallery", value: "GALLERY" }
              - { label: "Partners", value: "PARTNERS" }
          - label: "Images"
            name: "images"
            widget: "image"
            i18n: true
            media_library:
              config:
                multiple: true
          - label: "Title"
            name: "title"
            widget: "object"
            summary: "{{fields.text}}"
            i18n: true
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - {
                  label: "Highlighted text",
                  name: "highlight",
                  widget: "string",
                }
              - { label: "Icon", name: "icon", widget: "image" }
          - label: "Body"
            name: "body"
            widget: "markdown"
            i18n: true
          - label: "Buttons"
            name: "buttons"
            widget: "list"
            summary: "{{fields.title}}"
            i18n: true
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Link, name: link, widget: string }
              - { label: Secondary, name: secondary, widget: boolean }
          - label: "Numbers"
            name: "numbers"
            widget: "list"
            summary: "{{fields.text}}"
            i18n: true
            fields:
              - { label: Number, name: Number, widget: string }
              - { label: Text, name: text, widget: string }
          - label: "Carousel"
            name: "carousel"
            widget: "list"
            summary: "{{fields.highlight}}"
            i18n: true
            fields:
              - { label: Text, name: text, widget: string }
              - {
                  label: Highlighted text,
                  name: highlight,
                  widget: string,
                }
              - {
                  label: Text separator,
                  name: separator,
                  widget: string,
                  default: "=",
                }
              - { label: Large text, name: largeText, widget: string }
